name: Craft

on:
  workflow_dispatch:

jobs:
  craft-validator:
    name: Validation des crafts customs
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Pull repository
        run: |
          git pull && git rebase
      - name: Validation craft custom
        run: |
          php build/custom-craft-validator.php
  build-craft:
    name: Construction des crafts customs
    runs-on: ${{ matrix.image }}
    needs: [craft-validator]
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Pull repository
        run: |
          git pull && git rebase
      - name: Ajout librairies nécessaire
        run: |
          cd build && composer require shockedplot7560/craft-generator && cd ../
      - name: Construction craft custom
        run: |
          php build/build-custom-craft.php
      - name: Create Pull Request & Commit change
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Ajout des craft customs
          title: '[Craft] Mise à jour des crafts'
          body: >
            Ajout et modification des crafts custom
          labels: "Type: Craft"
          branch: custom-craft
