name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  skeletoncheck:
    name: Validation du skelette
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validations du skelette
        run: php build/check-skeleton.php docs skeleton
  namecheck:
    name: Validation des fichiers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validations du skelette
        run: php build/check-skeleton.php docs name