name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  codegen:
    name: Validation des fichiers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validations du skelette
        run: php build/generate-skeleton.php docs