name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  skeletoncheck:
    name: Skelette fichier
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Validations du skelette
        run: php build/file-skeleton-validator.php docs
  namecheck:
    name: Nom fichier
    needs: skeletoncheck
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Nommage des fichiers
        run: php build/file-name-validator.php docs
  unicitycheck:
    name: Unicité
    needs: skeletoncheck
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Unicité des ids
        run: php build/unicity-build-folder.php docs
  extract-pack:
    name: Extraction des pack de ressource
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Extraction
        run: php build/extract-pack.php
      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Extraction des ressource packs
          branch: ${{ github.ref }}
  craft-validator:
    name: Validation des crafts customs
    runs-on: ${{ matrix.image }}
    needs: extract-pack
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Validation craft custom
        run: |
          php build/custom-craft-validator.php
  build-craft:
    name: Construction des crafts customs
    runs-on: ${{ matrix.image }}
    needs: [extract-pack, craft-validator]
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Ajout librairies nécessaire
        run: |
          cd build && composer require shockedplot7560/craft-generator && cd ../
      - name: Construction craft custom
        run: |
          php build/build-custom-craft.php
      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Ajout des craft customs
          branch: ${{ github.ref }}
