name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  file-check:
    name: Vérification des fichiers
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Validations du skelette
        run: php build/file-skeleton-validator.php docs
      - name: Nommage des fichiers
        run: php build/file-name-validator.php docs
      - name: Unicité des ids
        run: php build/unicity-build-folder.php docs
      - name: Contenu des fichiers
        run: php build/file-content-validator.php docs
      - name: Validation craft custom
        run: php build/custom-craft-validator.php