name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  skeletoncheck:
    name: Skelette fichier
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Validations du skelette
        run: php build/file-skeleton-generator.php docs
  namecheck:
    name: Nom fichier
    needs: skeletoncheck
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Nommage des fichiers
        run: php build/file-name-validator.php docs
  unicitycheck:
    name: Unicité
    needs: skeletoncheck
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Unicité des ids
        run: php build/unicity-build-folder.php docs
  extract-pack:
    name: Extraction des pack de ressource
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.11]
    steps:
      - uses: actions/checkout@v2
      - name: Extraction
        run: php build/extract-pack.php
      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Extraction des ressource packs
          branch: ${{ github.ref }}
